<?php
include(dirname(__DIR__).'/framework/imanager.php');

/**
 * Create new image with images
 */
$category = $imanager->getCategory(1);
$field = $category->getField('name=images');
$fieldMarkup = new \Imanager\FieldFileupload();
$timestamp_images = time();

if(!$imanager->input->get->itemid) {
	$item = new \Imanager\Item($category->id);
} else {
	$item = $category->getItem((int) $imanager->input->get->itemid);
}

if($item && $imanager->input->post->action == 'save')
{
	// Intercept timestamp in order to identify the temporary folder later
	if($imanager->input->post->timestamp_images) {
		$timestamp_images = (int) $imanager->input->post->timestamp_images;
	}
	// Save it first if it's a new item
	if(!$item->id) {
		$item->set('name', 'Autogenerated Item');
		$item->save();
	}
	// We can only save images if item already exists
	if($item->id) {
		// Prepare input value
		$dataSent = array(
			'file' => $imanager->input->post->position_images,
			'title' => $imanager->input->post->title_images,
			'timestamp' => $timestamp_images
		);
		$result = $item->set('images', $dataSent);
		if($result !== true) {
			echo 'Error: field value could not be set';
		} else {
			if($item->save()) {
				\Imanager\Util::redirect("?itemid={$item->id}");
			}
		}
	}
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>Page Title</title>
	<meta name="description" content="">
	<!-- Mobile-friendly viewport -->
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">
	<!-- js stuff -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
</head>
<body>
<main role="main">
<?php
echo '<form action="" method="post">';

$fieldMarkup->set('url', '../framework/');
$fieldMarkup->set('action', '../framework/imanager/upload/server/php/index.php');
$fieldMarkup->set('id', $field->name);
$fieldMarkup->set('categoryid', $field->categoryid);
$fieldMarkup->set('itemid', $item->id);
$fieldMarkup->set('timestamp', $timestamp_images);
$fieldMarkup->set('fieldid', $field->id);
$fieldMarkup->set('configs', $field->configs, false);
$fieldMarkup->set('name', $field->name);

echo $fieldMarkup->render();
echo $fieldMarkup->renderJsLibs();

echo '<input type="hidden" name="action" value="save">';
echo '<button type="submit">Save</button>';

echo '</form>';
?>
</main>
<footer role="contentinfo">
	<div>Page footer content</div>
	<small>Copyright &copy; <time datetime="2018">2018</time> Ehret Studio</small>
</footer>
</body>
</html>
